using System.IO;
using ArenaDuel.Audio;
using ArenaDuel.Characters;
using ArenaDuel.Combat;
using ArenaDuel.Core;
using ArenaDuel.Data;
using ArenaDuel.UI;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;

namespace ArenaDuel.EditorTools
{
    public static class ArenaDuelProjectBuilder
    {
        const string Generated = "Assets/Generated";
        const string DataPath = Generated + "/Data";
        const string PrefabPath = Generated + "/Prefabs";
        const string ScenePath = "Assets/Scenes";
        const string Marker = Generated + "/.arena-duel-built";

        [InitializeOnLoadMethod]
        static void ScheduleFirstBuild()
        {
            if (!File.Exists(Marker)) EditorApplication.delayCall += () =>
            {
                if (!EditorApplication.isCompiling && !EditorApplication.isPlayingOrWillChangePlaymode)
                    BuildProject();
            };
        }

        [MenuItem("Arena Duel/Build/Rebuild Playable Project")]
        public static void BuildProject()
        {
            EnsureFolder("Assets", "Generated"); EnsureFolder(Generated, "Data"); EnsureFolder(Generated, "Prefabs"); EnsureFolder(Generated, "Rendering");
            EnsureFolder("Assets", "Scenes");
            ConfigureProject();
            HeroDefinition hero = CreateData();
            GameObject fighter = CreateFighterPrefab(hero);
            hero.characterPrefab = fighter; EditorUtility.SetDirty(hero); AssetDatabase.SaveAssets();
            CreateBootScene(); CreateMainMenuScene(hero); CreateHeroSelectScene(hero); CreateArenaScene(hero, fighter);
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(ScenePath + "/Boot.unity", true),
                new EditorBuildSettingsScene(ScenePath + "/MainMenu.unity", true),
                new EditorBuildSettingsScene(ScenePath + "/HeroSelect.unity", true),
                new EditorBuildSettingsScene(ScenePath + "/Arena.unity", true)
            };
            File.WriteAllText(Marker, "Generated by ArenaDuelProjectBuilder. Delete this file to rebuild automatically.\n");
            AssetDatabase.ImportAsset(Marker); AssetDatabase.SaveAssets(); AssetDatabase.Refresh();
            EditorSceneManager.OpenScene(ScenePath + "/Boot.unity");
            Debug.Log("Arena Duel playable project generated. Open Boot.unity and press Play.");
        }

        static void ConfigureProject()
        {
            EditorSettings.serializationMode = SerializationMode.ForceText;
            PlayerSettings.productName = "Arena Duel";
            PlayerSettings.companyName = "Arena Duel Studio";
            PlayerSettings.SetApplicationIdentifier(NamedBuildTarget.Android, "com.arenaduel.game");
            PlayerSettings.defaultInterfaceOrientation = UIOrientation.LandscapeLeft;
            PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARM64;
            PlayerSettings.SetScriptingBackend(NamedBuildTarget.Android, ScriptingImplementation.IL2CPP);
            PlayerSettings.SetIl2CppCompilerConfiguration(NamedBuildTarget.Android, Il2CppCompilerConfiguration.Release);
            PlayerSettings.Android.minSdkVersion = AndroidSdkVersions.AndroidApiLevel26;
            PlayerSettings.Android.targetSdkVersion = AndroidSdkVersions.AndroidApiLevelAuto;
            PlayerSettings.colorSpace = ColorSpace.Linear;
            PlayerSettings.MTRendering = true;

            const string rendererPath = Generated + "/Rendering/ArenaRenderer.asset";
            const string pipelinePath = Generated + "/Rendering/ArenaURP.asset";
            UniversalRendererData renderer = AssetDatabase.LoadAssetAtPath<UniversalRendererData>(rendererPath);
            if (!renderer) { renderer = ScriptableObject.CreateInstance<UniversalRendererData>(); AssetDatabase.CreateAsset(renderer, rendererPath); }
            UniversalRenderPipelineAsset pipeline = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(pipelinePath);
            if (!pipeline) { pipeline = ScriptableObject.CreateInstance<UniversalRenderPipelineAsset>(); AssetDatabase.CreateAsset(pipeline, pipelinePath); }
            SerializedObject pipelineSO = new SerializedObject(pipeline);
            SerializedProperty list = pipelineSO.FindProperty("m_RendererDataList");
            if (list != null) { list.arraySize = 1; list.GetArrayElementAtIndex(0).objectReferenceValue = renderer; }
            SerializedProperty index = pipelineSO.FindProperty("m_DefaultRendererIndex"); if (index != null) index.intValue = 0;
            pipelineSO.ApplyModifiedPropertiesWithoutUndo();
            GraphicsSettings.defaultRenderPipeline = pipeline; QualitySettings.renderPipeline = pipeline;
            ConfigureQualityTiers();
        }

        static void ConfigureQualityTiers()
        {
            Object[] assets = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/QualitySettings.asset");
            if (assets == null || assets.Length == 0) return;
            SerializedObject so = new SerializedObject(assets[0]); SerializedProperty levels = so.FindProperty("m_QualitySettings");
            if (levels == null) return;
            while (levels.arraySize < 4) levels.InsertArrayElementAtIndex(levels.arraySize);
            string[] names = { "LOW", "MEDIUM", "HIGH", "ULTRA" };
            float[] shadows = { 18f, 28f, 42f, 60f }; int[] aa = { 0, 2, 4, 4 }; int[] vSync = { 0, 0, 0, 0 };
            for (int i = 0; i < levels.arraySize; i++)
            {
                if (i >= 4) { levels.DeleteArrayElementAtIndex(i--); continue; }
                SerializedProperty level = levels.GetArrayElementAtIndex(i);
                SetString(level, "name", names[i]); SetFloat(level, "shadowDistance", shadows[i]); SetInt(level, "antiAliasing", aa[i]); SetInt(level, "vSyncCount", vSync[i]);
                SetInt(level, "textureQuality", i == 0 ? 1 : 0); SetInt(level, "shadowCascades", i < 2 ? 1 : 2); SetInt(level, "pixelLightCount", i + 1);
            }
            so.ApplyModifiedPropertiesWithoutUndo();
        }

        static HeroDefinition CreateData()
        {
            SkillDefinition basic = Skill("BasicAttack", "Flame Edge", SkillKind.Melee, 95, .65f, 2.2f, 1.1f, 2f, StatusKind.None, 0, 0);
            SkillDefinition skill1 = Skill("Skill1", "Cinder Bolt", SkillKind.Projectile, 140, 5f, 10f, .5f, 2.5f, StatusKind.Burn, 3f, 12f);
            SkillDefinition skill2 = Skill("Skill2", "Blazing Rush", SkillKind.DashStrike, 170, 8f, 4.2f, 1.6f, 4f, StatusKind.Stun, .55f, 0);
            SkillDefinition ultimate = Skill("Ultimate", "Inferno Ring", SkillKind.Area, 260, 20f, 4.5f, 4.5f, 5f, StatusKind.Burn, 4f, 18f);
            string path = DataPath + "/EmberDefinition.asset";
            HeroDefinition hero = AssetDatabase.LoadAssetAtPath<HeroDefinition>(path);
            if (!hero) { hero = ScriptableObject.CreateInstance<HeroDefinition>(); AssetDatabase.CreateAsset(hero, path); }
            hero.heroId = "ember"; hero.displayName = "Ember"; hero.description = "A relentless arena duelist who turns heat and momentum into pressure.";
            hero.maxHealth = 1000; hero.attack = 100; hero.defense = 25; hero.movementSpeed = 5.5f; hero.acceleration = 20; hero.jumpForce = 7.5f;
            hero.basicAttack = basic; hero.skill1 = skill1; hero.skill2 = skill2; hero.ultimate = ultimate; EditorUtility.SetDirty(hero); return hero;
        }

        static SkillDefinition Skill(string id, string display, SkillKind kind, float damage, float cooldown, float range, float radius, float knockback, StatusKind status, float duration, float magnitude)
        {
            string path = DataPath + "/" + id + ".asset"; SkillDefinition skill = AssetDatabase.LoadAssetAtPath<SkillDefinition>(path);
            if (!skill) { skill = ScriptableObject.CreateInstance<SkillDefinition>(); AssetDatabase.CreateAsset(skill, path); }
            skill.skillId = id; skill.displayName = display; skill.kind = kind; skill.damage = damage; skill.cooldown = cooldown; skill.range = range; skill.radius = radius;
            skill.knockback = knockback; skill.status = status; skill.statusDuration = duration; skill.statusMagnitude = magnitude; skill.windup = kind == SkillKind.Area ? .4f : .12f; skill.movementLock = kind == SkillKind.Area ? .65f : .25f;
            skill.projectileSpeed = 14f; skill.description = display + " — provisional Ember ability; replace values after legacy audit."; EditorUtility.SetDirty(skill); return skill;
        }

        static GameObject CreateFighterPrefab(HeroDefinition hero)
        {
            GameObject root = new GameObject("Ember");
            CharacterController cc = root.AddComponent<CharacterController>(); cc.height = 1.86f; cc.radius = .36f; cc.center = new Vector3(0, .93f, 0); cc.stepOffset = .3f;
            MovementController movement = root.AddComponent<MovementController>(); HealthController health = root.AddComponent<HealthController>(); root.AddComponent<StatusEffectController>();
            root.AddComponent<CooldownSystem>(); root.AddComponent<ComboSystem>(); CombatController combat = root.AddComponent<CombatController>(); FighterController fighter = root.AddComponent<FighterController>();
            Transform visual = new GameObject("VisualRoot").transform; visual.SetParent(root.transform, false);
            GameObject source = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Art/Characters/Ember/Ember.fbx");
            if (source) { GameObject model = (GameObject)PrefabUtility.InstantiatePrefab(source); model.name = "EmberModel"; model.transform.SetParent(visual, false); }
            else { GameObject fallback = GameObject.CreatePrimitive(PrimitiveType.Capsule); fallback.name = "EmberFallback"; fallback.transform.SetParent(visual, false); fallback.transform.position = Vector3.up; }
            Transform attack = Marker(root.transform, "AttackOrigin", new Vector3(0, 1.05f, .75f));
            Transform projectile = Marker(root.transform, "ProjectileOrigin", new Vector3(0, 1.25f, .65f));
            Marker(root.transform, "VFXOrigin", new Vector3(0, 1f, 0)); Marker(root.transform, "GroundCheck", new Vector3(0, .08f, 0));
            Transform hurtbox = Marker(root.transform, "HurtboxRoot", new Vector3(0, .93f, 0)); CapsuleCollider hurtCollider = hurtbox.gameObject.AddComponent<CapsuleCollider>(); hurtCollider.isTrigger = true; hurtCollider.height = 1.7f; hurtCollider.radius = .34f; hurtbox.gameObject.AddComponent<HurtboxController>();
            fighter.hero = hero; fighter.modelRoot = visual; movement.definition = hero; health.definition = hero; combat.hero = hero; combat.attackOrigin = attack; combat.projectileOrigin = projectile;
            string path = PrefabPath + "/Ember.prefab"; GameObject prefab = PrefabUtility.SaveAsPrefabAsset(root, path); Object.DestroyImmediate(root); return prefab;
        }

        static Transform Marker(Transform parent, string name, Vector3 localPosition) { Transform t = new GameObject(name).transform; t.SetParent(parent, false); t.localPosition = localPosition; return t; }

        static UnityEngine.Camera CreateCamera()
        {
            GameObject go = new GameObject("Main Camera", typeof(UnityEngine.Camera), typeof(AudioListener)); go.tag = "MainCamera";
            UnityEngine.Camera cam = go.GetComponent<UnityEngine.Camera>(); cam.nearClipPlane = .08f; cam.farClipPlane = 120f; return cam;
        }

        static void CreateBootScene()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single); new GameObject("GameBootstrap", typeof(GameBootstrap)); new GameObject("AudioManager", typeof(AudioManager));
            EditorSceneManager.SaveScene(scene, ScenePath + "/Boot.unity");
        }
        static void CreateMainMenuScene(HeroDefinition hero)
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single); CreateCamera(); MainMenuUI ui = new GameObject("MainMenu", typeof(MainMenuUI)).GetComponent<MainMenuUI>(); ui.ember = hero;
            EditorSceneManager.SaveScene(scene, ScenePath + "/MainMenu.unity");
        }
        static void CreateHeroSelectScene(HeroDefinition hero)
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single); CreateCamera(); HeroSelectUI ui = new GameObject("HeroSelect", typeof(HeroSelectUI)).GetComponent<HeroSelectUI>(); ui.ember = hero;
            EditorSceneManager.SaveScene(scene, ScenePath + "/HeroSelect.unity");
        }
        static void CreateArenaScene(HeroDefinition hero, GameObject fighter)
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single); CreateCamera(); ArenaMatchController match = new GameObject("ArenaMatchController", typeof(ArenaMatchController)).GetComponent<ArenaMatchController>(); match.ember = hero; match.fighterPrefab = fighter;
            EditorSceneManager.SaveScene(scene, ScenePath + "/Arena.unity");
        }

        static void EnsureFolder(string parent, string name) { string path = parent + "/" + name; if (!AssetDatabase.IsValidFolder(path)) AssetDatabase.CreateFolder(parent, name); }
        static void SetString(SerializedProperty p, string name, string value) { SerializedProperty v = p.FindPropertyRelative(name); if (v != null) v.stringValue = value; }
        static void SetFloat(SerializedProperty p, string name, float value) { SerializedProperty v = p.FindPropertyRelative(name); if (v != null) v.floatValue = value; }
        static void SetInt(SerializedProperty p, string name, int value) { SerializedProperty v = p.FindPropertyRelative(name); if (v != null) v.intValue = value; }
    }
}
